### ISSUE TITLE
team-145-galbas

### ISSUE THREAD

**Issue by dibdas** [IjayAbby/Enumerable-Methods#6]
You should refactor the readme file to add how to run tests

 Remove all debuging codes like the p statements which are left from your codes

 Edit this Pull Request's name, make it descriptive and meaningful. I mean that it should reflect the work you are implementing on this Pull Request, currently its name is code review => that name doesna't reflect the actual work that you are implementing in it.

**Comment by IjayAbby** [comment]
Fix TSE requirements and the project has been approved.
